name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or '16'

    - name: Install dependencies
      run: npm install
      
   - name: Build app
     env:
       CI: false
    run: npm run build


    - name: Push changes to main branch
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "dhwani.dasadia@gmail.com"
        git config --local user.name "dhwani1602"
        git add .
        git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
